package com.GeoFlex.GeoFlexBackend.PoJo.Route;

/**
 * Generic PoJo class generated by a converter.
 */
public class Content{
    public String answer;
    public boolean correct;
    public String id;
}
