package com.GeoFlex.GeoFlexBackend.PoJo.Route;
import java.util.ArrayList;

/**
 * Generic PoJo class generated by a converter.
 */
public class Location{
    public String name;
    public String text_info;
    public String id;
    public ArrayList<Content> content;
    public String data;
    public String location_index;
    public String last_location;
    public float x_coodinate;
    public float y_coodinate;
    public String directions;
}
