package com.GeoFlex.GeoFlexBackend.PoJo.Route;

import java.util.ArrayList;

/**
 * Generic PoJo class generated by a converter.
 */
public class Route{
    public String title;
    public String description;
    public String type;
    public String id;
    public String code;
    public ArrayList<Media> media;
    public ArrayList<Location> location;
    public int locations;
    public String timesFinished;
}
