package com.GeoFlex.GeoFlexBackend.PoJo;
import java.util.ArrayList;
import java.util.List;

/**
 * Generic PoJo class generated by a converter.
 */
public class Location{
    public String name;
    public String text_info;
    public String id;
    public ArrayList<Content> content;
    public String data;
}
