package com.GeoFlex.GeoFlexBackend.PoJo;
import java.util.ArrayList;
import java.util.List;

/**
 * Generic PoJo class generated by a converter.
 */
public class Route{
    public String title;
    public String description;
    public String type;
    public String id;
    public String code;
    public ArrayList<Location> location;
    public int locations;
}
